name: Release

on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.tag-name || github.event.release.tag_name }}

permissions: write-all
# permissions:
#   contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    environment:
      # Note: this environment is protected
      name: Release
    steps:
      - uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
