name: Release

on:
  release:
    types:
      - released
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.tag-name || github.event.release.tag_name }}

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    environment:
      # Note: this environment is protected
      name: Release

    steps:
      - id: prep
        uses: pbrisbin/publish-action/pb/v0.4
        with:
          update-tag: false

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.prep.outputs.sha }}

      - run: |
          git tag --force "$TAG" "$SHA"
          git push --tags
        env:
          SHA: ${{ steps.prep.outputs.sha }}
          TAG: ${{ steps.prep.outputs.major-tag }}
